### ISSUE TITLE
PHP warning when there is no functions.php

### ISSUE THREAD

**Issue by thefuxia** [mpeshev/Theme-Mentor#2]
When I tested the [Mini Theme](https://github.com/toscho/Toscho-s-Mini-Theme) – which was never meant to pass any test :) – I got a warning in the admin screen:

> Warning: file(path/to/themes/toscho-mini-theme/functions.php): failed to open stream: No such file or directory in /path/to/plugins/theme-mentor/theme-mentor.php on line 115

Add a `file_exists()` check before you try to read a file.

**Comment by mpeshev** [comment]
Good call for the error, but just pushed another solution that is closer to the impl. Will now check the other commit proposals (also, you're props'ed for the last commit)
